### ISSUE TITLE
Create a page with instructions to register

### ISSUE THREAD

**Issue by stelita** [freeflowpages/freeflow-threebot-login#1]
Create a top menu that opens a page with the instructions to register.
There will be screenshots and videos with the steps as shown[ in this doc ](https://docs.google.com/document/d/1rYZTBVwfd3T6qq3uMaAj1rqRvXwTpltZXwyDgA55u7Y/edit#)

There is also a video that I have shared with @ehab-hassan that should also be shared here

The look should be clean, for example, [similar to this](https://www.ledger.com/start/)

**Comment by ehab-hassan** [comment]
done at staging 
https://www.staging.freeflowpages.com/threebot_login/how
and waiting @Hamdy  to merge to production

**Comment by ehab-hassan** [comment]
done at production
https://www.freeflowpages.com/user/auth/login
